[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aiogram"
description = 'Modern and fully asynchronous framework for Telegram Bot API'
readme = "README.rst"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Alex Root Junior", email = "jroot.junior@gmail.com" },
]
maintainers = [
    { name = "Alex Root Junior", email = "jroot.junior@gmail.com" },
]
keywords = [
    "telegram",
    "bot",
    "api",
    "framework",
    "wrapper",
    "asyncio",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Framework :: AsyncIO",
    "Typing :: Typed",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Communications :: Chat",
]
dependencies = [
    "magic-filter~=1.0.9",
    "aiohttp~=3.8.3",
    "pydantic~=1.10.4",
    "aiofiles~=22.1.0",
    "certifi>=2022.9.24",
]
dynamic = ["version"]

[tool.hatch.version]
path = "aiogram/__init__.py"

[project.optional-dependencies]
fast = [
    "uvloop>=0.17.0; sys_platform == 'darwin' or sys_platform == 'linux'",
]
redis = [
    "redis~=4.3.4",
]
proxy = [
    "aiohttp-socks~=0.7.1",
]
i18n = [
    "Babel~=2.9.1",
]
test = [
    "pytest~=7.1.3",
    "pytest-html~=3.1.1",
    "pytest-asyncio~=0.19.0",
    "pytest-lazy-fixture~=0.6.3",
    "pytest-mock~=3.9.0",
    "pytest-mypy~=0.10.0",
    "pytest-cov~=4.0.0",
    "pytest-aiohttp~=1.0.4",
    "aresponses~=2.1.6",
]
docs = [
    "Sphinx~=5.2.3",
    "sphinx-intl~=2.0.1",
    "sphinx-autobuild~=2021.3.14",
    "sphinx-copybutton~=0.5.0",
    "furo~=2022.9.29",
    "sphinx-prompt~=1.5.0",
    "Sphinx-Substitution-Extensions~=2022.2.16",
    "towncrier~=22.8.0",
    "pygments~=2.4",
    "pymdown-extensions~=9.6",
    "markdown-include~=0.7.0",
    "Pygments~=2.13.0",
    "sphinxcontrib-towncrier~=0.3.1a3",
]

[project.urls]
Homepage = "https://aiogram.dev/"
Documentation = "https://docs.aiogram.dev/"
Repository = "https://github.com/aiogram/aiogram/"

[tool.hatch.envs.default]
features = [
    "fast",
    "redis",
    "proxy",
    "i18n",
]
dependencies = [
    "black~=22.8",
    "isort~=5.11",
    "ruff~=0.0.215",
    "mypy~=0.981",
    "toml~=0.10.2",
    "pre-commit~=2.20.0",
    "packaging~=21.3",
    "typing-extensions~=4.3.0",
]
post-install-commands = [
    "pre-commit install",
]

[tool.hatch.envs.default.scripts]
reformat = [
    "black aiogram tests",
    "isort aiogram tests",
]
lint = "ruff aiogram"

[tool.hatch.envs.docs]
features = [
    "fast",
    "redis",
    "proxy",
    "i18n",
    "docs",
]
[tool.hatch.envs.docs.scripts]
serve = "sphinx-autobuild --watch aiogram/ --watch CHANGELOG.rst --watch README.rst docs/ docs/_build/ {args}"

[tool.hatch.envs.dev]
python = "3.10"
features = [
    "fast",
    "redis",
    "proxy",
    "i18n",
    "test",
]
extra-dependencies = [
    "butcher @ git+https://github.com/aiogram/butcher.git@v0.1.9"
]

[tool.hatch.envs.test]
features = [
    "fast",
    "redis",
    "proxy",
    "i18n",
    "test",
]

[tool.hatch.envs.test.scripts]
cov = [
    "pytest --cov-config pyproject.toml --cov=aiogram --html=reports/py{matrix:python}/tests/index.html {args}",
    "coverage html -d reports/py{matrix:python}/coverage",
]
cov-redis = [
    "pytest --cov-config pyproject.toml --cov=aiogram --html=reports/py{matrix:python}/tests/index.html --redis {env:REDIS_DNS:'redis://localhost:6379'} {args}",
    "coverage html -d reports/py{matrix:python}/coverage",
]
view-cov = "google-chrome-stable reports/py{matrix:python}/coverage/index.html"


[[tool.hatch.envs.test.matrix]]
python = ["38", "39", "310", "311"]

[tool.ruff]
line-length = 99
select = [
    # "C", # TODO: mccabe - code complecity
    "C4",
    "E",
    "F",
    "T10",
    "T20",
    "Q",
    "RET",
    "I"
]
src = ["aiogram", "tests"]
exclude = [
    ".git",
    "build",
    "dist",
    "venv",
    ".venv",
    "docs",
    "tests",
    "dev",
    "scripts",
    "*.egg-info",
]
target-version = "py310"

[tool.ruff.isort]
known-first-party = [
    "aiogram",
    "finite_state_machine",
    "handlers",
    "routes",
]

[tool.ruff.per-file-ignores]
"aiogram/client/bot.py" = ["E501"]
"aiogram/types/*" = ["E501"]
"aiogram/methods/*" = ["E501"]
"aiogram/enums/*" = ["E501"]


[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = [
    "tests",
]

[tool.coverage.run]
branch = true
parallel = true
omit = [
    "aiogram/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
    "if __name__ == .__main__.:",
    "pragma: no cover",
    "if TYPE_CHECKING:",
    "@abstractmethod",
    "@overload",
]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "mypy-aiofiles"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "mypy-async_lru"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "mypy-uvloop"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "mypy-redis.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "mypy-babel.*"
ignore_missing_imports = true

[tool.black]
line-length = 99
target-version = ['py38', 'py39', 'py310', 'py311']
exclude = '''
(
    \.eggs
  | \.git
  | \.tox
  | build
  | dist
  | venv
  | docs
)
'''

[tool.isort]
profile = "black"

[tool.towncrier]
package = "aiogram"
filename = "CHANGES.rst"
directory = "CHANGES/"
template = "CHANGES/.template.rst.jinja2"
issue_format = "`#{issue} <https://github.com/aiogram/aiogram/issues/{issue}>`_"

[[tool.towncrier.section]]
path = ""

[[tool.towncrier.type]]
directory = "feature"
name = "Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bugfixes"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Improved Documentation"
showcontent = true

[[tool.towncrier.type]]
directory = "removal"
name = "Deprecations and Removals"
showcontent = true

[[tool.towncrier.type]]
directory = "misc"
name = "Misc"
showcontent = true
